package com.sahaya.app.ui

data class AppStrings(
    val appSubtitle: String,
    val highUrgency: String,
    val mediumUrgency: String,
    val lowUrgency: String,
    val searchPlaceholder: String,
    val emptyDatabase: String,
    val noResults: String,
    val mothersLabel: String,
    val childrenLabel: String,
    val visitedOnPrefix: String,
    val noRecentVisit: String,
    val villagePrefix: String,
    val categoryPrefix: String,
    val incomePrefix: String,
    val activeFamilyContext: String,
    val askAboutFamilyBtn: String,
    val immunoTitle: String,
    val noChildrenText: String,
    val maternalTitle: String,
    val noMothersText: String,
    val ancCountLabel: String,
    val lmpLabel: String,
    val riskSignsLabel: String,
    val recentCheckupsLabel: String,
    val dateLabel: String,
    val bpLabel: String,
    val schemesTitle: String,
    val noSchemesText: String,
    val voiceTitle: String,
    val generalProtocolMode: String,
    val familyContextMode: (String) -> String,
    val newConversationBtn: String,
    val greetingMessage: String,
    val listeningPlaceholder: String,
    val typeOrSpeakPlaceholder: String,
    val followupCue: String,
    val confidenceLabel: String,
    val officialSourcesLabel: String,
    val listenAudioBtn: String,
    val quickPrompt1: String,
    val quickPrompt2: String,
    val quickPrompt3: String
)

val HindiStrings = AppStrings(
    appSubtitle = "फील्ड सहायक • ग्राम रामपुर",
    highUrgency = "अति आवश्यक",
    mediumUrgency = "मध्यम",
    lowUrgency = "सामान्य",
    searchPlaceholder = "नाम या कारण खोजें...",
    emptyDatabase = "डेटाबेस में कोई परिवार दर्ज नहीं है।",
    noResults = "कोई परिणाम नहीं मिला।",
    mothersLabel = "माताएं",
    childrenLabel = "बच्चे",
    visitedOnPrefix = "को भेंट",
    noRecentVisit = "हाल में कोई भेंट नहीं",
    villagePrefix = "ग्राम",
    categoryPrefix = "श्रेणी",
    incomePrefix = "आय वर्ग",
    activeFamilyContext = "📍 सक्रिय परिवार संदर्भ",
    askAboutFamilyBtn = "🎙️ इस परिवार के बारे में सवाल पूछें",
    immunoTitle = "💉 टीकाकरण स्थिति (UIP Schedule)",
    noChildrenText = "इस परिवार में कोई पंजीकृत बच्चा नहीं है।",
    maternalTitle = "🤰 मातृ स्वास्थ्य एवं ANC जांच",
    noMothersText = "इस परिवार में कोई पंजीकृत माता नहीं है।",
    ancCountLabel = "एएनसी जांच संख्या",
    lmpLabel = "अंतिम मासिक धर्म (LMP)",
    riskSignsLabel = "जोखिम संकेत",
    recentCheckupsLabel = "हालिया क्लिनिकल जांच:",
    dateLabel = "तिथि",
    bpLabel = "रक्तचाप",
    schemesTitle = "🏛️ सरकारी योजना पात्रता (Schemes)",
    noSchemesText = "कोई विशेष योजना मिलान दर्ज नहीं है।",
    voiceTitle = "सहया संवाद सहायक",
    generalProtocolMode = "📍 सामान्य प्रोटोकॉल मोड",
    familyContextMode = { name -> "📍 संदर्भ: $name का परिवार" },
    newConversationBtn = "नयी बातचीत",
    greetingMessage = "नमस्ते आशा दीदी! मैं सहया हूँ। टीकाकरण, गर्भावस्था जोखिम या सरकारी योजनाओं से जुड़ा कोई भी सवाल बोलकर या लिखकर पूछें।",
    listeningPlaceholder = "सुन रहा हूँ... बोलिए",
    typeOrSpeakPlaceholder = "सवाल बोलें या लिखें...",
    followupCue = "सुन रहा हूँ... अगला सवाल पूछें (संदर्भ सुरक्षित है)",
    confidenceLabel = "✓ आत्मविश्वास स्कोर:",
    officialSourcesLabel = "आधिकारिक स्रोत उद्धरण:",
    listenAudioBtn = "उत्तर सुनें",
    quickPrompt1 = "ओपीवी टीका अनुसूची क्या है?",
    quickPrompt2 = "गर्भावस्था में उच्च रक्तचाप के खतरे क्या हैं?",
    quickPrompt3 = "पीएमएमवीवाई योजना में क्या लाभ हैं?"
)

val EnglishStrings = AppStrings(
    appSubtitle = "Field Assistant • Village Rampur",
    highUrgency = "High Priority",
    mediumUrgency = "Medium",
    lowUrgency = "Routine",
    searchPlaceholder = "Search name or reasons...",
    emptyDatabase = "No households registered in the database.",
    noResults = "No matching households found.",
    mothersLabel = "Mothers",
    childrenLabel = "Children",
    visitedOnPrefix = "visited on",
    noRecentVisit = "No recent visit recorded",
    villagePrefix = "Village",
    categoryPrefix = "Category",
    incomePrefix = "Income",
    activeFamilyContext = "📍 Active Household Context",
    askAboutFamilyBtn = "🎙️ Ask questions about this family",
    immunoTitle = "💉 Immunization Tracker (UIP Schedule)",
    noChildrenText = "No children registered in this household.",
    maternalTitle = "🤰 Maternal Health & ANC Checkups",
    noMothersText = "No pregnant women/mothers registered in this household.",
    ancCountLabel = "ANC Visits Completed",
    lmpLabel = "Last Menstrual Period (LMP)",
    riskSignsLabel = "Maternal Risk Flags",
    recentCheckupsLabel = "Recent Clinical Checkups:",
    dateLabel = "Date",
    bpLabel = "Blood Pressure",
    schemesTitle = "🏛️ Government Scheme Eligibility",
    noSchemesText = "No scheme matches recorded.",
    voiceTitle = "Sahaya Voice Assistant",
    generalProtocolMode = "📍 General Protocol Mode",
    familyContextMode = { name -> "📍 Context: $name's family" },
    newConversationBtn = "New Chat",
    greetingMessage = "Hello ASHA Didi! I am Sahaya. Ask any protocol question regarding immunization, pregnancy risks, or government schemes by voice or text.",
    listeningPlaceholder = "Listening... please speak now",
    typeOrSpeakPlaceholder = "Speak or type your question...",
    followupCue = "Listening for follow-up... (context retained)",
    confidenceLabel = "✓ Confidence Score:",
    officialSourcesLabel = "Official Protocol Sources:",
    listenAudioBtn = "Listen",
    quickPrompt1 = "When are OPV doses scheduled?",
    quickPrompt2 = "What are the dangers of high blood pressure in pregnancy?",
    quickPrompt3 = "What are the benefits under PMMVY scheme?"
)

val TamilStrings = AppStrings(
    appSubtitle = "கள உதவியாளர் • ராம்பூர் கிராமம்",
    highUrgency = "மிக அவசரம்",
    mediumUrgency = "நடுத்தரம்",
    lowUrgency = "வழக்கமானது",
    searchPlaceholder = "பெயர் அல்லது காரணத்தை தேடவும்...",
    emptyDatabase = "தரவுத்தளத்தில் குடும்பங்கள் எதுவும் பதிவு செய்யப்படவில்லை.",
    noResults = "முடிவுகள் எதுவும் கிடைக்கவில்லை.",
    mothersLabel = "தாய்கள்",
    childrenLabel = "குழந்தைகள்",
    visitedOnPrefix = "பார்வையிட்ட நாள்",
    noRecentVisit = "சமீபத்திய பார்வை இல்லை",
    villagePrefix = "கிராமம்",
    categoryPrefix = "பிரிவு",
    incomePrefix = "வருமானம்",
    activeFamilyContext = "📍 செயலில் உள்ள குடும்ப சூழல்",
    askAboutFamilyBtn = "🎙️ இந்த குடும்பம் பற்றி கேள்வி கேட்கவும்",
    immunoTitle = "💉 தடுப்பூசி நிலை (UIP அட்டவணை)",
    noChildrenText = "இந்த குடும்பத்தில் குழந்தைகள் பதிவு செய்யப்படவில்லை.",
    maternalTitle = "🤰 தாய்வழி சுகாதாரம் & ANC பரிசோதனை",
    noMothersText = "இந்த குடும்பத்தில் தாய்மார்கள் பதிவு செய்யப்படவில்லை.",
    ancCountLabel = "ANC வருகை எண்ணிக்கை",
    lmpLabel = "கடைசி மாதவிடாய் தேதி (LMP)",
    riskSignsLabel = "ஆபத்து அறிகுறிகள்",
    recentCheckupsLabel = "சமீபத்திய மருத்துவ பரிசோதனை:",
    dateLabel = "தேதி",
    bpLabel = "இரத்த அழுத்தம்",
    schemesTitle = "🏛️ அரசு திட்ட தகுதி (Schemes)",
    noSchemesText = "திட்ட பொருத்தங்கள் எதுவும் இல்லை.",
    voiceTitle = "சகாயா குரல் உதவியாளர்",
    generalProtocolMode = "📍 பொது நெறிமுறை முறை",
    familyContextMode = { name -> "📍 சூழல்: $name குடும்பம்" },
    newConversationBtn = "புதிய உரையாடல்",
    greetingMessage = "வணக்கம் ஆஷா சகோதரி! நான் சகாயா. தடுப்பூசி, கர்ப்ப ஆபத்துகள் அல்லது அரசு திட்டங்கள் குறித்த கேள்விகளை பேசவோ எழுதவோ செய்யலாம்.",
    listeningPlaceholder = "கேட்கிறேன்... பேசுங்கள்",
    typeOrSpeakPlaceholder = "கேள்வியை பேசவும் அல்லது தட்டச்சு செய்யவும்...",
    followupCue = "தொடர் கேள்வியை கேட்கிறேன்... (சூழல் பாதுகாப்பானது)",
    confidenceLabel = "✓ நம்பிக்கை மதிப்பெண்:",
    officialSourcesLabel = "அதிகாரப்பூர்வ ஆதாரங்கள்:",
    listenAudioBtn = "பதிலை கேட்கவும்",
    quickPrompt1 = "OPV தடுப்பூசி அட்டவணை என்ன?",
    quickPrompt2 = "கர்ப்ப காலத்தில் உயர் இரத்த அழுத்தத்தின் ஆபத்துகள் என்ன?",
    quickPrompt3 = "PMMVY திட்டத்தின் நன்மைகள் என்ன?"
)

fun getStrings(lang: String): AppStrings {
    return when (lang) {
        "en" -> EnglishStrings
        "ta" -> TamilStrings
        else -> HindiStrings
    }
}
