# Project-wide Gradle settings.

# Memory allocation for Gradle Daemon and D8 dexing
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC

# Enable AndroidX and auto-migrate dependencies
android.useAndroidX=true

# Speed up build performance and reduce dex size
android.nonTransitiveRClass=true
kotlin.code.style=official
